# This is the age that you dont want anyone younger joining
age: 13
# either true or false, whether or not you want new players position locked untill age checked
lock: true
# the command to execute when player is over set age
success: default
# the command to execute when player is not over set age
failure: default
# whether or not to display players age with the /birthdays command
birthdaysage: false