name: AgeChecker
main: com.github.thelonedevil.AgeChecker.App
version: 3
commands:
   DOB:
      description: This command registers your date of birth with the server
      usage: /<command> [DD/MM/YYYY]
   bypass:
      description: This command registers your date of birth with the server
      usage: /<command> [target player] [true or false]
   list:
      description: This command registers your date of birth with the server
      usage: /<command> <target player>